---
Name: rootroutes
---
SilverStripe\Control\Director:
  rules:
    '': SilverStripe\Control\Controller
---
Name: coreroutes
After:
  - '#rootroutes'
---
SilverStripe\Control\Director:
  rules:
    'Security//$Action/$ID/$OtherID': SilverStripe\Security\Security
    'CMSSecurity//$Action/$ID/$OtherID': SilverStripe\Security\CMSSecurity
    'dev//$Action/$ID/$OtherID': SilverStripe\Dev\DevelopmentAdmin #mwuits added //$Action/$ID/$OtherID 2018-01-26
    'interactive': SilverStripe\Dev\SapphireREPL
    'InstallerTest//$Action/$ID/$OtherID': SilverStripe\Dev\InstallerTest
    'SapphireInfo//$Action/$ID/$OtherID': SilverStripe\Dev\SapphireInfo
    'SapphireREPL//$Action/$ID/$OtherID': SilverStripe\Dev\SapphireREPL
---
Name: security-limited
After:
  - '#rootroutes'
Except:
  environment: dev
---
SilverStripe\Control\Director:
  rules:
      'Security//$Action/$ID/$OtherID': '%$RateLimitedSecurityController'
